export const TUTORIAL_STEP_TRANSLATIONS_FR: Record<
  string,
  { title?: string; body?: string; suggestion?: string; role?: string }
> = {
  welcome: {
    title: "Tableau de bord flotte",
    body: "Voici la vue d'accueil: disponibilite, indicateurs de reparation, ordres de travail ouverts et trajets actifs. Utilisez la barre laterale pour acceder a chaque workflow.",
    suggestion: "Ensuite vous parcourrez les trajets, controles et ordres de travail avec des donnees reelles.",
  },
  "status-grid": {
    title: "Comptage des statuts vehicules",
    body: "Ces tuiles resumment les vehicules operationnels, deployes, en maintenance, en attente de pieces ou immobilises. Le panneau d'alertes signale aussi les echeances de vignette (60 / 30 jours et expiree).",
  },
  "dashboard-panels": {
    title: "Trajets et ordres de travail en un coup d'oeil",
    body: "Les trajets actifs, les ordres de travail recents et les alertes critiques apparaissent ici. Ouvrez les pages detaillees depuis la navigation pour agir.",
  },
  "nav-vehicles": {
    title: "Vehicules",
    body: "La section Vehicules sert a enregistrer les actifs, definir la categorie (4x4, camion, engin, etc.) et ouvrir la fiche de chaque unite.",
  },
  "vehicles-list": {
    title: "Registre des vehicules",
    body: "Parcourez le tableau de flotte, filtrez par statut et ajoutez de nouveaux vehicules. Chaque ligne ouvre l'historique maintenance, trajets, controles et TCO.",
    suggestion: "Demo: un vehicule temporaire TUT- est cree pour ce tutoriel puis supprime a la fin.",
  },
  "vehicles-add": {
    title: "Ajouter un vehicule (CRUD)",
    body: "Utilisez Ajouter un vehicule pour saisir code, marque/modele, categorie et base. Le code doit etre unique dans votre organisation.",
    suggestion: "Exemple: TUT-R1, Ford Ranger, categorie 4x4, base HQ.",
  },
  "vehicles-open-detail": {
    title: "Ouvrir la fiche vehicule",
    body: "Cliquez sur un code vehicule pour ouvrir sa fiche: statut, historique, tracker et actions rapides.",
    suggestion: "Ouvrez une ligne avant de passer a l'etape suivante.",
  },
  "vehicles-status-change": {
    title: "Changer le statut operationnel / maintenance",
    body: "Le changement rapide pilote le cycle de vie. Certains statuts exigent un ordre de travail ouvert; le systeme bloque sinon et propose des alternatives. Le statut radie exige une validation management et un motif.",
    suggestion: "Clore un ordre de travail ne remet pas automatiquement le vehicule en operationnel.",
  },
  "nav-trips": {
    title: "Trajets (checkout operationnel)",
    body: "Les trajets representent la sortie reelle du vehicule: conducteur, itineraire, chargement et retour. La planification mission et les demandes de type vehicule restent dans Requests.",
  },
  "trips-checkout": {
    title: "Check-out / check-in",
    body: "Utilisez Check Out Vehicle pour demarrer un trajet et Check In au retour. Les trajets termines alimentent l'historique et le kilometrage.",
    suggestion: "Exemple: HQ -> MAS avec kilometrage issu du controle conducteur.",
  },
  "trips-loadout": {
    title: "Manifestes de chargement (Asset Management)",
    body: "Les listes de chargement sont creees dans AM. Collez l'ID de document AM pour lier un manifeste au trajet, puis ouvrez-le dans AM pour le detail.",
    suggestion: "Le lien/delien du manifeste requiert un niveau Manager.",
  },
  "nav-checks": {
    title: "Controles pre-deploiement",
    body: "Le controle conducteur est un gate avant de partir. Les echecs peuvent necessiter une validation manager.",
  },
  "vehicle-checks-new": {
    title: "Nouveau controle vehicule",
    body: "Remplissez les listes electricite, fluides, conduite et equipements. L'envoi cree une trace auditable liee au vehicule.",
  },
  "nav-work-orders": {
    title: "Ordres de travail et job cards",
    body: "Les ordres de travail suivent les reparations: statut, affectation, main d'oeuvre, pieces et liens PR/PO.",
  },
  "work-orders-list": {
    title: "Pipeline maintenance",
    body: "Creez des interventions depuis les remontes terrain ou inspections, faites-les progresser puis cloturez avec couts et immobilisation.",
  },
  "nav-maintenance": {
    title: "Maintenance planifiee",
    body: "Planifiez les services par kilometrage et date. Les retards peuvent generer des alertes et, si active, des ordres de travail automatiques.",
  },
  "nav-requests": {
    title: "Demandes vehicule",
    body: "Creez d'abord une mission approuvee, puis demandez une classe de vehicule. Le management approuve la ligne; la flotte assigne ensuite un vehicule pool.",
  },
  "nav-inspections": {
    title: "Inspections",
    body: "Checklists structurees: pre-depart, mecanique detaillee, preparation transfert transfrontalier ou modele complet. Les echecs peuvent creer des ordres de travail.",
  },
  "inspections-peek": {
    title: "Checklists d'inspection",
    body: "Creez une inspection via le bouton et consultez l'historique dans la liste. Pour les mouvements internationaux, utilisez les modeles mecaniques appropries.",
  },
  "nav-country-transfers": {
    title: "Transferts pays",
    body: "Cette zone sert a traiter la file d'approbation. Pour soumettre un changement, ouvrez une fiche vehicule puis Request change dans Country / organization.",
  },
  "country-transfers-peek": {
    title: "Approvals de transfert",
    body: "Les fleet leads approuvent les corrections de saisie; les executives approuvent les secondements et transferts permanents avec preuves mission et inspection.",
  },
  "nav-map": {
    title: "Carte flotte",
    body: "Positions GPS en direct ou dernier point connu selon equipement tracker. Depuis un marqueur, ouvrez le vehicule ou le trajet actif.",
  },
  "nav-tco": {
    title: "TCO et analytics",
    body: "Analyse du cout total de possession, scoring fin de vie et performance par cohortes, alimentee par maintenance, kilometrage et achats.",
  },
  "nav-reports": {
    title: "Rapports et exports",
    body: "Telechargez des exports CSV pour vehicules, trajets, controles, maintenance, TCO et audits.",
  },
  "nav-daily": {
    title: "Mise a jour quotidienne (WhatsApp)",
    body: "Generez un resume texte depuis les notes et changements du jour, puis copiez/editez avant publication WhatsApp.",
  },
  finish: {
    title: "Termine",
    body: "Vous avez couvert les principaux workflows. La fin du tutoriel supprime les donnees demo (codes TUT-) creees pour l'exercice.",
    suggestion: "Cliquez sur Terminer le tutoriel pour nettoyer les donnees et fermer le parcours.",
  },
  "dvc-intro": {
    title: "Workflow controle conducteur",
    body: "Ce mini-parcours couvre le controle pre-deploiement: creation, formulaire, notation des lignes, verification equipements et envoi.",
    suggestion: "Assurez-vous d'etre sur Vehicle Checks.",
  },
  "dvc-new": { title: "1. Demarrer un nouveau controle", body: "Utilisez New check pour ouvrir le formulaire de controle conducteur." },
  "dvc-form": { title: "2. Remplir le formulaire", body: "Une soumission regroupe direction, vehicule/conducteur, odometre avec photo, photos exterieures, route, lignes pass/fail, equipements et remarques." },
  "dvc-direction": { title: "3. Selection direction", body: "Choisissez Departing ou Returning. Pour un depart, la date de retour est obligatoire et doit etre au moins egale a la date de depart." },
  "dvc-photos": { title: "4. Photos requises", body: "Ajoutez l'odometre puis les photos exterieures demandees. Elles servent d'evidence et de reference etat." },
  "dvc-lines": { title: "5. Noter les lignes", body: "Passez chaque ligne en Pass/Fail et decrivez les anomalies. Les echecs alimentent le suivi maintenance." },
  "dvc-equip": { title: "6. Verifier les equipements", body: "Confirmez la disponibilite des equipements de securite et d'operation avant validation finale." },
  "dvc-submit": { title: "7. Soumettre", body: "Envoyez le controle. Le resultat est enregistre dans l'historique du vehicule et peut declencher des actions aval." },
  "insp-intro": { title: "Workflow inspection mecanique", body: "Ce parcours montre la creation d'une inspection, la navigation des sections et l'envoi d'un resultat exploitable." },
  "insp-new": { title: "1. Nouvelle inspection", body: "Utilisez New inspection pour demarrer un controle structure pour le vehicule cible." },
  "insp-tabs": { title: "2. Sections de checklist", body: "Les onglets organisent les domaines de controle pour faciliter la saisie et la revue complete." },
  "insp-form": { title: "3. Remplir et conclure", body: "Renseignez les points, indiquez les echecs et fournissez un statut global clair." },
  "insp-submit": {
    title: "4. Soumettre l'inspection",
    body: "Soumettez l'inspection; les echecs peuvent alimenter le pipeline maintenance.",
    suggestion: "Un Fail peut creer un ordre de travail prioritaire.",
  },
  "fd-nav": {
    title: "Workflow deploiement terrain",
    body: "Ce parcours suit le chemin complet: mission, approbation management, reservation flotte, controle conducteur et check-out trajet.",
    role: "Tous",
    suggestion: "Un bac a sable mission + vehicule TUT- est cree puis supprime en fin de tutoriel.",
  },
  "fd-new-mission": {
    title: "1. Soumettre une mission",
    body: "Ouvrez + New mission puis completez dates, destination, classe vehicule et contexte d'intervention.",
    role: "Planificateur / demandeur",
  },
  "fd-mission-form": {
    title: "2. Verifier le formulaire mission",
    body: "La mission est la source de verite pour approbation et reservation flotte. Apres soumission, elle attend validation management.",
    role: "Planificateur / demandeur",
    suggestion: "Si le formulaire est ferme, rouvrez + New mission.",
  },
  "fd-mgmt-approve": {
    title: "3. Approuver la mission",
    body: "Les profils autorises approuvent ou rejettent avec motif. Sans approbation, la flotte et les conducteurs ne peuvent pas continuer.",
    role: "Approbateur management",
  },
  "fd-fleet-reserve": {
    title: "4. Reserver un vehicule pool",
    body: "La flotte assigne un vehicule disponible selon classe demandee, planning et contraintes operationnelles.",
    role: "Manager / lead flotte",
  },
  "fd-calendar": {
    title: "5. Verifier le calendrier",
    body: "Le calendrier aide a visualiser disponibilites, conflits et arbitrages potentiels avant depart.",
    role: "Flotte / visibilite",
  },
  "fd-dvc-start": {
    title: "6. Lancer le controle depart",
    body: "Le conducteur qui part ouvre un controle vehicule lie a la mission.",
    role: "Conducteur au depart",
  },
  "fd-dvc-form": {
    title: "7. Completer le controle",
    body: "Renseignez odometre, photos, points de securite et remarques pour valider l'aptitude au depart.",
    role: "Conducteur au depart",
  },
  "fd-trips-open": {
    title: "8. Ouvrir les trajets",
    body: "Une fois les gates satisfaits, ouvrez la page Trips pour effectuer le check-out mission lie.",
    role: "Conducteur / dispatch",
  },
  "fd-checkout-form": {
    title: "9. Faire le check-out mission",
    body: "Completez conducteur, mission, vehicule, itineraire et infos de chargement avant depart effectif.",
    role: "Conducteur / dispatch",
  },
  "fd-readiness": {
    title: "10. Lire les gates readiness",
    body: "Les verifications readiness consolident l'etat mission, vehicule et conformite avant autorisation de sortie.",
    role: "Conducteur / dispatch",
  },
  "fd-loadout": {
    title: "11. Lier le manifeste de chargement",
    body: "Associez un manifeste AM au trajet pour tracer les equipements transportes.",
    role: "Conducteur / logistique",
  },
  "fd-arbitration": {
    title: "12. Arbitrage capacite management",
    body: "Si la capacite est insuffisante sur une date de depart, le management arbitre les missions a maintenir, differer ou annuler.",
    role: "Management (capacite)",
  },
  "fd-dashboard-alerts": {
    title: "13. Alertes tableau de bord",
    body: "Le dashboard remonte les alertes critiques du workflow terrain (retards, blocages checkout, fenetres vignette).",
    role: "Management / supervision",
  },
  "vr-intro": { title: "Demande de vehicule", body: "Ce parcours couvre la creation d'une demande, le routage de destination et l'affectation pool." },
  "vr-button": { title: "1. Ouvrir une nouvelle demande", body: "Utilisez + New mission / demande selon votre flux pour demarrer une demande de vehicule." },
  "vr-form": { title: "2. Completer la demande", body: "Renseignez mission, classe vehicule, dates et informations operationnelles utiles a l'approbation." },
  "vr-route": { title: "3. Verifier destination et itineraire", body: "Le systeme peut afficher distance estimee et elements de trajet pour aider planification et carburant." },
  "vr-pool": { title: "4. Affectation flotte", body: "Apres approbation, la flotte assigne un vehicule pool compatible et confirme la ligne demandee." },
  "loadout-intro": { title: "Manifestes de chargement", body: "Ce mini-parcours montre ou lier et consulter les manifestes Asset Management sur les trajets." },
  "loadout-section": { title: "Section manifeste", body: "Dans la section manifeste, collez l'ID document AM, ouvrez le document et deliez si necessaire." },
  "ct-intro": { title: "Transferts pays / organisation", body: "Ce parcours couvre approbation de file et soumission de changement depuis la fiche vehicule." },
  "ct-approvals": { title: "1. File d'approbation", body: "Traitez les demandes selon type: correction de donnees, secondement ou transfert permanent." },
  "ct-open-vehicle": { title: "2. Ouvrir la fiche vehicule", body: "Depuis le registre, ouvrez la fiche de l'unite concernee pour lancer la demande de changement." },
  "ct-vehicle-card": { title: "3. Carte Country / organization", body: "Utilisez Request change, choisissez le type de mouvement et joignez les justificatifs requis." },
  "ct-inspection": { title: "4. Piece inspection", body: "Pour un transfert reel, joignez les preuves mission et inspection mecanique conformes." },
  "ehs-intro": { title: "Registre conducteurs EHS", body: "Ce parcours montre comment filtrer, verifier documents, tests et autorisations conducteur." },
  "ehs-page": { title: "1. Ouvrir la page EHS", body: "Accedez au registre pour consulter et maintenir les profils conducteurs approuves." },
  "ehs-country-filter": { title: "2. Filtre pays / organisation", body: "Filtrez le registre par organisation pour afficher uniquement les conducteurs pertinents." },
  "ehs-hr-picker": { title: "3. Recherche collaborateur", body: "Utilisez le selecteur RH pour rattacher un enregistrement conducteur a la bonne personne." },
  "ehs-drivers-list": { title: "4. Liste des conducteurs", body: "La liste centralise statut, validite et informations de conformite pour chaque conducteur." },
  "ehs-license": { title: "5. Permis et validites", body: "Renseignez type de permis, date d'expiration et preuves pour controle de conformite." },
  "ehs-tests": { title: "6. Tests pratiques", body: "Enregistrez les tests de conduite et leurs resultats pour confirmer l'aptitude." },
  "ehs-assessments": { title: "7. Evaluations", body: "Suivez les evaluations theorique/pratique et maintenez un historique verifiable." },
  "ehs-authorizations": { title: "8. Autorisations", body: "Definissez les habilitations (vehicules, engins, restrictions) selon le profil valide." },
  "ehs-attest": { title: "9. Attestation", body: "Utilisez l'attestation pour confirmer officiellement les informations saisies." },
  "ehs-effect-checks": { title: "10. Impact sur les controles", body: "Seuls les conducteurs valides dans ce registre peuvent etre selectionnes dans les workflows depart mission." },
  "pvr-intro": { title: "Remboursement vehicule personnel (F006)", body: "Ce parcours couvre eligibilite, pieces jointes, details trajet et lignes de remboursement." },
  "pvr-page": { title: "1. Ouvrir la page PVR", body: "Accedez a l'ecran de demande pour consulter et creer un remboursement vehicule personnel." },
  "pvr-eligibility": { title: "2. Eligibilite", body: "Confirmez les criteres d'eligibilite avant de saisir les couts et distances." },
  "pvr-attachments": { title: "3. Pieces jointes", body: "Ajoutez les documents justificatifs (preuves, recus, approbations) requis par la politique." },
  "pvr-trip-details": { title: "4. Details trajet", body: "Saisissez origine, destination, dates et kilometrage pour etablir la base de calcul." },
  "pvr-claims": { title: "5. Lignes de remboursement", body: "Entrez les montants et categories de depense selon les regles internes." },
  "pvr-export": { title: "6. Export / suivi", body: "Exportez les demandes pour revue, validation finance et archivage." },
  "fi-intro": { title: "Incident terrain -> ordre de travail", body: "Ce parcours montre comment declarer un incident puis creer le suivi maintenance." },
  "fi-page": { title: "1. Ouvrir Report Issue", body: "Utilisez la page Report Issue pour declarer un probleme detecte sur le terrain." },
  "fi-form": { title: "2. Remplir le signalement", body: "Renseignez vehicule, symptomes, gravite et pieces jointes pour qualifier l'incident." },
  "fi-nav-work-orders": { title: "3. Basculer vers Work Orders", body: "Depuis la navigation, ouvrez Work Orders pour transformer ou suivre le ticket en intervention." },
  "fi-follow-up": { title: "4. Suivi de resolution", body: "Affectez, mettez a jour le statut, ajoutez pieces/main d'oeuvre et cloturez quand la reparation est terminee." },
  "wo-intro": { title: "Creer un ordre de travail", body: "Ce mini-parcours couvre creation rapide et verification de l'apparition dans le pipeline." },
  "wo-button": { title: "1. Bouton New work order", body: "Depuis Work Orders, cliquez New work order pour ouvrir le formulaire de creation." },
  "wo-form": { title: "2. Renseigner l'intervention", body: "Choisissez vehicule, titre, description, type, priorite, mecanicien et lieu de reparation." },
  "wo-after": { title: "3. Apres creation", body: "La nouvelle intervention apparait dans la liste. Ouvrez-la pour suivi, liens PR/PO et progression jusqu'a completion." },
};
